server:
  port: 9527
spring:
  application:
    name: zuul

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
    instance:
      instance-id: gateway-9527.com
      prefer-ip-address: true


info:
  app.name: atguigu-microcloud
  company.name: www.atguigu.com
  build.artifactId: zuul
  build.version: 1.0-SNAPSHOT


